steps:
  # Step 0: Build Frontend Docker Image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build'
    args:
      - 'build'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/cloud-run-source-deploy/${_REPO_NAME}/${_SERVICE_NAME}:${COMMIT_SHA}'
      - '-f'
      - '${_DOCKERFILE}'
      - '.'

  # Step 1: Push Image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push'
    args:
      - 'push'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/cloud-run-source-deploy/${_REPO_NAME}/${_SERVICE_NAME}:${COMMIT_SHA}'

  # Step 2: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    id: 'Deploy'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}'
      - '--image'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/cloud-run-source-deploy/${_REPO_NAME}/${_SERVICE_NAME}:${COMMIT_SHA}'
      - '--region'
      - '${_DEPLOY_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '${_MEMORY}'
      - '--cpu'
      - '${_CPU}'
      - '--timeout'
      - '${_TIMEOUT}'
      - '--max-instances'
      - '10'
      - '--min-instances'
      - '0'
      - '--set-env-vars'
      - 'API_URL=${_API_URL}'

substitutions:
  _SERVICE_NAME: empathic-frontend
  _DOCKERFILE: Dockerfile.frontend
  _DEPLOY_REGION: europe-west1
  _REGION: europe-west1
  _REPO_NAME: empathicgateway
  _MEMORY: 1Gi
  _CPU: '1'
  _TIMEOUT: '300'
  _API_URL: https://empathic-backend-1078757655479.europe-west1.run.app

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'
